### ISSUE TITLE
Issue with  mc_bin_client.py

### ISSUE THREAD

**Issue by paramita1024** [JannerM/trajectory-transformer#13]
While trying to run your given script, I faced following problems.
Traceback (most recent call last):
  File "scripts/train.py", line 6, in <module>
    import trajectory.utils as utils
  File "/home/rs/18CS91P06/Bill_payment/trajectory-transformer-master/trajectory/utils/__init__.py", line 1, in <module>
    from .setup import Parser, watch
  File "/home/rs/18CS91P06/Bill_payment/trajectory-transformer-master/trajectory/utils/setup.py", line 6, in <module>
    from tap import Tap
  File "/home/rs/18CS91P06/anaconda3/envs/trajectory/lib/python3.8/site-packages/tap.py", line 6, in <module>
    from mc_bin_client import mc_bin_client, memcacheConstants as Constants
  File "/home/rs/18CS91P06/anaconda3/envs/trajectory/lib/python3.8/site-packages/mc_bin_client/mc_bin_client.py", line 14, in <module>
    from memcacheConstants import REQ_MAGIC_BYTE, RES_MAGIC_BYTE
ModuleNotFoundError: No module named 'memcacheConstants'

**Comment by jannerm** [comment]
Can you give the result of `conda list` and `pip freeze`? That might help narrow down the dependency issue.

**Comment by paramita1024** [comment]
Thanks. It is working now.

Regards,

Paramita Koley

Ph.D. Student, CSE

Indian Institute Of Technology, Kharagpur

**Comment by paramita1024** [comment]
Thanks.

Regards,

Paramita Koley

Ph.D. Student, CSE

Indian Institute Of Technology, Kharagpur

**Comment by 664730** [comment]
> Can you give the result of `conda list` and `pip freeze`? That might help narrow down the dependency issue.

May I ask how you resolved it? Thank you.
